# SPDX-License-Identifier: GPL-3.0-or-later
"""Cadrille ComfyUI nodes (includes CAD-Recode)."""

from .cadrille_nodes import (
    NODE_CLASS_MAPPINGS as CADRILLE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CADRILLE_NODE_DISPLAY_NAME_MAPPINGS
)

from .cadrecode_nodes import (
    NODE_CLASS_MAPPINGS as CADRECODE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CADRECODE_NODE_DISPLAY_NAME_MAPPINGS
)

NODE_CLASS_MAPPINGS = {
    **CADRILLE_NODE_CLASS_MAPPINGS,
    **CADRECODE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CADRILLE_NODE_DISPLAY_NAME_MAPPINGS,
    **CADRECODE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
